apiVersion: apps/v1
kind: Deployment

metadata:
  name: static-deployment
  namespace: static-system

spec:
  replicas: 3

  selector:
    matchLabels:
      app: static

  template:
    metadata:
      labels:
        app: static

    spec:
      containers:
        - name: static-container 
          image: nginx:latest
          ports:
            - containerPort: 80