grafana:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 3d

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-prometheus
          volumeName: prometheus-pv
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

