grafana:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 3d

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    additionalScrapeConfigs:
      - job_name: calico-felix
        static_configs:
          - targets:
              - 172.16.2.11:9091
              - 172.16.2.101:9091
              - 172.16.2.102:9091

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-prometheus
          volumeName: prometheus-pv
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

